version: '3.1'

services:
  sql-stream-store:
    container_name: sss-example-server
    image: sqlstreamstore/server:1.2.0-beta.3.12-alpine3.8
    ports:
      - "5000:80"
    networks:
      - app-network
      - db-network
    environment:
      - SQLSTREAMSTORE_PROVIDER=postgres
      - SQLSTREAMSTORE_CONNECTION_STRING=Host=pgbouncer;Port=6432;User Id=postgres;Database=example;Pooling=false;
    depends_on:
      - pgbouncer

  database:
    container_name: sss-example-postgres
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    networks:
      - db-network

  pgbouncer:
    container_name: sss-example-pgbouncer
    image: brainsam/pgbouncer:1.7.2
    environment:
      DB_HOST: database
      DB_USER: postgres           # define credentials
      DB_PORT: 5432               # define database
    links:
      - database
    ports:
      - "6432:6432"               # PgBouncer port
    networks:
      - db-network
    depends_on:
      - database

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
