name: CI
on:
  push:
    branches:
      - refs/pull/*/merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: build
        run: "./build.sh"