name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  docker-hub-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docker Hub Documentation
        uses: ./.github/actions/docker-tag-list
  continuous-integration:
    strategy:
      fail-fast: false
      matrix:
        env:
          - library-version: 1.2.0-beta.5
            container-runtime-version: 2.2.5
            container-runtime: alpine3.9
            runtime: alpine-x64
            os-version: Alpine 3.9
          - library-version: 1.2.0-beta.5
            container-runtime-version: 2.2.5
            container-runtime: alpine3.8
            runtime: alpine-x64
            os-version: Alpine 3.8
          - library-version: 1.2.0-beta.5
            container-runtime-version: 2.2.5
            container-runtime: stretch-slim
            runtime: debian.9-x64
            os-version: Debian 9
          - library-version: 1.2.0-beta.5
            container-runtime-version: 2.2.5
            container-runtime: bionic
            runtime: ubuntu.18.04-x64
            os-version: Ubuntu 18.04
    runs-on: ubuntu-latest
    name: continuous-integration/github/${{ matrix.env.container-runtime }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: build
        run: "./build.sh"
        env:
          REMOTE_IMAGE: sqlstreamstore/server
          LIBRARY_VERSION: ${{ matrix.env.library-version }}
          CONTAINER_RUNTIME_VERSION: ${{ matrix.env.container-runtime-version }}
          CONTAINER_RUNTIME: ${{ matrix.env.container-runtime }}
          RUNTIME: ${{ matrix.env.runtime }}
      - name: Docker Login
        uses: actions/docker/login@fe7ed3c
        if: github.event_name == 'push'
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Docker Push
        uses: actions/docker/cli@fe7ed3c
        if: github.event_name == 'push'
        with:
          args: push sqlstreamstore/server